{
 "title": "Tripp Lite UPS Dashboard",
 "description": "Inspiration taken from \nhttps://technicalramblings.com/blog/setting-grafana-influxdb-telegraf-ups-monitoring-unraid/\n\nUpdating https://grafana.com/grafana/dashboards/7197 to work with Telegraf apcupsd integration for simpler/easier automation of retrieving APC information",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kwhprice", "label": "kWh Price", "query": "1.25" },
   {
    "name": "maxwatt",
    "label": "UPS Max Output Power Capacity (Watt)",
    "query": "500,600,700,800,865,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,1980,2000,2200"
   },
   { "name": "currency", "label": "Currency", "query": "$,€,£,C$,kr,₽,¥,R" },
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Original Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "This Month Consumption/Costs - Original",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "alias": "Costs",
       "expr": "sum(sum_over_time(tripplite_output_power_watts[24h]) * 0.000012 * 24)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "measurement": "apcupsd",
       "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "load_percent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           "/100*$maxwatt/1000/60*$kwhprice"
          ],
          "type": "math"
         }
        ]
       ]
      },
      {
       "alias": "kWh",
       "expr": "sum_over_time(tripplite_output_power_watts[1h]) * 0.000012 * 24 * $kwhprice",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "measurement": "apcupsd",
       "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "load_percent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Month Power Consumption/Costs - original",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "alias": "Costs",
       "expr": "sum(sum_over_time(tripplite_output_power_watts[24h]) * 0.000012 * 24)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "measurement": "apcupsd",
       "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "load_percent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           "/100*$maxwatt/1000/60*$kwhprice"
          ],
          "type": "math"
         }
        ]
       ]
      },
      {
       "alias": "kWh",
       "expr": "sum_over_time(tripplite_output_power_watts[24h]) * 0.000012 * 24 * $kwhprice *.01",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "__auto",
       "measurement": "apcupsd",
       "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "load_percent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "This Years Consumption/Costs - Original",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "kwatth", "label": "Load" }
     ],
     "targets": [
      {
       "alias": "Costs",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "apcupsd",
       "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "load_percent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           "/100*$maxwatt/1000/60*$kwhprice"
          ],
          "type": "math"
         }
        ]
       ]
      },
      {
       "alias": "kWh",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "apcupsd",
       "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "load_percent" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Customized Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "UPS Load %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "UPS Load",
     "expr": "(tripplite_config_power_watts/tripplite_output_power_watts)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100*$maxwatt" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Percent",
     "expr": "tripplite_current_charge_pct",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "/100*$maxwatt/1000/60*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100*$maxwatt" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100*$maxwatt" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load kWh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wh",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Week's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Week Consumption/Costs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Costs",
     "expr": "sum(sum_over_time(tripplite_output_power_watts[24h]) * 0.000012 * 24)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "/100*$maxwatt/1000/60*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    },
    {
     "alias": "kWh",
     "expr": "sum_over_time(tripplite_output_power_watts[1h]) * 0.000012 * 24 * 1.25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Month Consumption/Costs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Costs",
     "expr": "sum(sum_over_time(tripplite_output_power_watts[24h]) * 0.000012 * 24)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "/100*$maxwatt/1000/60*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    },
    {
     "alias": "kWh",
     "expr": "sum_over_time(tripplite_output_power_watts[1h]) * 0.000012 * 24 * 1.25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Week's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "/100*$maxwatt/1000/60*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Month's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Month's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "/100*$maxwatt/1000/60*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Year's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last 7 Day Power Consumption/Costs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Costs",
     "expr": "sum_over_time(tripplite_output_power_watts[1h]) * 0.000012 * 24 * $kwhprice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "/100*$maxwatt/1000/60*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    },
    {
     "alias": "kWh",
     "expr": "sum(sum_over_time(tripplite_output_power_watts[24h]) * 0.000012 * 24)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/100*$maxwatt/1000/60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Year's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "/100*$maxwatt/1000/60*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24*365" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "/100*$maxwatt/1000*24*$kwhprice*365"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Load vs Time left",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 22 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 0.01 * $maxwatt" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "T",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "TIMELEFT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}